site_name: TV Time - Docs

repo_name: "TV Time"
repo_url: "https://github.com/rabelzx/REQ-FGA-2024-1"

nav:
  - Início: index.md
  - Pré-rastreabilidade:
    - RichPicture: Pre-rastreabilidade/richpicture.md
  - Atas: 
    - Dia 23/07: Atas/reuniao_23_07.md
    - Dia 25/07: Atas/reuniao_25_07.md
    - Dia 29/07: Atas/reuniao_29_07.md
    - Dia 30/07: Atas/reuniao_30_07.md

theme:
  name: material

  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy

  language: pt

  font:
    text: "Roboto"
    code: "sans-serif"

  palette:
    - scheme: slate 
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: yellow

    - scheme: default
      toggle:
        icon: material/toggle-switch
      primary: yellow

  logo: images/app_logo.png
  favicon: images/app_logo.png

extra_css:
  - css/style.css

markdown_extensions:
  - attr_list
  - md_in_html