site_name: TV Time

repo_name: "TV Time"
repo_url: "https://github.com/mdsreq-fga-unb/2024.1-CONSTRUMIX"

nav:
  - Início: index.md
  - Rastreabilidade:
    - Dia 25/07: rastreabilidade/reuniao_25_07.md
    - Dia 29/07: rastreabilidade/reuniao_29_07.md
  - RichPicture:
    - RichPicture: rich_picture/rich_index.md
    - teste: rich_picture/rich1.md

theme:
  name: material

  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy

  language: pt

  font:
    text: "Roboto"
    code: "sans-serif"

  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: yellow

    - scheme: slate
      toggle:
        icon: material/toggle-switch
      primary: yellow

  logo: images/logo.png
  favicon: images/logo.png

extra_css:
  - css/style.css


markdown_extensions:
  - attr_list
  - md_in_html