site_name: TV Time - Docs

repo_name: "TV Time"
repo_url: "https://github.com/rabelzx/REQ-FGA-2024-1"

nav:
  - Início: index.md

  - Pré-rastreabilidade:
    - RichPicture: Pre-rastreabilidade/richpicture.md
  - Elicitação:
    - Sobre: Elicitacao/elicitacao.md
    - Brainstorming: Elicitacao/brainstorm.md
    - Observação: Elicitacao/observacao.md
    - Análise de Protocolo: Elicitacao/analise.md
    - Requisitos Elicitados: Elicitacao/requisitos.md
    - Priorização: Elicitacao/priorizacao.md
  - Modelagem:
    - Visão do Produto: Modelagem/VisaoProduto/visao_produto.md
    - Cenários: Modelagem/Cenarios/cenarios.md
    - Léxico: Modelagem/Lexico/lexico.md
    - Diagrama de Casos de Uso: Modelagem/CasosUsos/casosUsos.md
    - Especificação de Casos de Uso: Modelagem/CasosUsos/espCasosUsos.md
    - Especificação Suplementar: Modelagem/EspecificacaoSuplementar/EspecificacaoSuplementar.md
    - Backlog do Produto: Modelagem/Agil/Backlog.md
    - Sprint Backlog: Modelagem/Agil/SprintBacklog.md
    - NFR Framework: Modelagem/NFR/nfr.md
  - Atas: 
    - Dia 23/07: Atas/reuniao_23_07.md
    - Dia 25/07: Atas/reuniao_25_07.md
    - Dia 29/07: Atas/reuniao_29_07.md
    - Dia 30/07: Atas/reuniao_30_07.md
    - Dia 31/07: Atas/reuniao_31_07.md
    - Dia 06/08: Atas/reuniao_06_08.md
    - Dia 13/08: Atas/reuniao_13_08.md
    - Dia 20/08: Atas/reuniao_20_08.md
  - Entregas: Entregas/entregas.md

theme:
  name: material

  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy

  language: pt

  font:
    text: "Roboto"
    code: "sans-serif"

  palette:
    - scheme: slate 
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: yellow

    - scheme: default
      toggle:
        icon: material/toggle-switch
      primary: yellow

  logo: images/app_logo.png
  favicon: images/app_logo.png


markdown_extensions:
  - attr_list
  - md_in_html